services:
  musicxmldb.postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./.containers/musicxmldb-db:/var/lib/postgresql/data

  musicxmldb.pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "9090:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - musicxmldb.postgres

  musicxmldb.keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: start-dev --verbose
    environment:
      KC_DB: postgres
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_DB_SCHEMA: ${KEYCLOAK_DB_SCHEMA}
      KC_DB_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}?currentSchema=${KEYCLOAK_DB_SCHEMA}

      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true

      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}

    volumes:
      - ./.containers/identity:/opt/keycloak/data
    ports:
      - "18080:8080"
    depends_on:
      - musicxmldb.postgres

  musicxmldb.server:
    image: ${DOCKER_REGISTRY-}musicxmldbserver
    container_name: server
    build:
      context: ./MusicXmlDb.Server/
      dockerfile: ./MusicXmlDb.Server/Dockerfile
    depends_on:
      - musicxmldb.postgres
    ports:
      - "8080:8080"
      - "8081:8081"

  musicxmldb.client:
    container_name: client
    build:
      context: ./MusicXmlDb.Client/
      dockerfile: ./Dockerfile
    ports:
      - "5173:8080"
    depends_on:
      - musicxmldb.server
