events { 
    worker_connections 1024; 
}

http {
    include /etc/nginx/mime.types;
    server {
        listen 8080;
        server_name localhost;

        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }

        location = /index.html {
            root /usr/share/nginx/html;
        }

        error_page 404 /index.html;
    }
}
