// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicXmlDb.Server.ScoreDocuments;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MusicXmlDb.Server.Migrations
{
    [DbContext(typeof(ScoreDocumentContext))]
    partial class ScoreDocumentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("score_documents")
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MusicXmlDb.Server.MusicXmlDocuments.MusicXmlDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<Guid>("ScoreDocumentHistoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("score_document_history_id");

                    b.HasKey("Id")
                        .HasName("pk_music_xml_document");

                    b.HasIndex("ScoreDocumentHistoryId")
                        .IsUnique()
                        .HasDatabaseName("ix_music_xml_document_score_document_history_id");

                    b.ToTable("music_xml_document", "score_documents");
                });

            modelBuilder.Entity("MusicXmlDb.Server.ScoreDocuments.ScoreDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<int>("Views")
                        .HasColumnType("integer")
                        .HasColumnName("views");

                    b.HasKey("Id")
                        .HasName("pk_score_document");

                    b.ToTable("score_document", "score_documents");
                });

            modelBuilder.Entity("MusicXmlDb.Server.ScoreDocuments.ScoreDocumentHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<Guid>("ScoreDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("score_document_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_score_document_history");

                    b.HasIndex("ScoreDocumentId")
                        .HasDatabaseName("ix_score_document_history_score_document_id");

                    b.ToTable("score_document_history", "score_documents");
                });

            modelBuilder.Entity("MusicXmlDb.Server.MusicXmlDocuments.MusicXmlDocument", b =>
                {
                    b.HasOne("MusicXmlDb.Server.ScoreDocuments.ScoreDocumentHistory", "ScoreDocumentHistory")
                        .WithOne("MusicXmlDocument")
                        .HasForeignKey("MusicXmlDb.Server.MusicXmlDocuments.MusicXmlDocument", "ScoreDocumentHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_music_xml_document_score_document_history_score_document_hi");

                    b.Navigation("ScoreDocumentHistory");
                });

            modelBuilder.Entity("MusicXmlDb.Server.ScoreDocuments.ScoreDocumentHistory", b =>
                {
                    b.HasOne("MusicXmlDb.Server.ScoreDocuments.ScoreDocument", "ScoreDocument")
                        .WithMany("History")
                        .HasForeignKey("ScoreDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_score_document_history_score_document_score_document_id");

                    b.Navigation("ScoreDocument");
                });

            modelBuilder.Entity("MusicXmlDb.Server.ScoreDocuments.ScoreDocument", b =>
                {
                    b.Navigation("History");
                });

            modelBuilder.Entity("MusicXmlDb.Server.ScoreDocuments.ScoreDocumentHistory", b =>
                {
                    b.Navigation("MusicXmlDocument")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
